pipeline {
    agent any

    stages {
        stage('Dotnet Build') {
            steps {
                // Coloca aquí los comandos o scripts para el Paso A
                // Por ejemplo: sh 'mi_comando'
              sh 'dotnet build'
            }
        }

        stage('Docker compose') {
            when {
                expression {
                    currentBuild.resultIsBetterOrEqualTo('SUCCESS')
                }
            }
            steps {
                script {
                    if (currentBuild.resultIsBetterOrEqualTo('SUCCESS')) {
                        // Ejecuta el comando 'dotnet build' en el Paso B
                        echo "aqui tendra que ir el docker compose?"
                        sh 'pwd'
                        //sh 'ls -R'
                        dir('we-working-api') {
                            //sh 'pwd'  // Opcional: mostrar el directorio actual después del cambio
                            sh 'ls -R'
                            // Cambiar al directorio 'we-working-api' dentro de 'we-working-api'
                            dir('we-working-api') {
                                //sh 'pwd'  // Opcional: mostrar el directorio actual después del cambio
                                sh 'ls -R'
                            }
                        }
                    } else {
                        currentBuild.result = 'FAILURE'
                        error('Paso A falló, por lo que Paso B se omite.')
                    }
                }
            }
        }
    }
}
